version: "3.5"

services:
  build:
    image: delegate-registry
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./build:/build:rw
    command: "yarn compile"