language: minimal

services:
  - docker

cache:
  directories:
    - node_modules

before_script: 
- cp .env.sample .env
- docker build -t delegate-registry .

jobs:
  include:
    - script:
      - docker run delegate-registry yarn test
    - script:
      - docker run delegate-registry yarn coverage